// Derived from E2B Runtime's Apache-2.0 envd process contract.
// Pinned source revision: 767ceb4b2ec0e598f512767c8da9e5e6618da368.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: internal/backend/e2b/wire/process.proto

package wireconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	wire "github.com/infercrane/brezel/internal/backend/e2b/wire"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProcessName is the fully-qualified name of the Process service.
	ProcessName = "process.Process"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProcessConnectProcedure is the fully-qualified name of the Process's Connect RPC.
	ProcessConnectProcedure = "/process.Process/Connect"
	// ProcessStartProcedure is the fully-qualified name of the Process's Start RPC.
	ProcessStartProcedure = "/process.Process/Start"
)

// ProcessClient is a client for the process.Process service.
type ProcessClient interface {
	Connect(context.Context, *connect.Request[wire.ConnectRequest]) (*connect.ServerStreamForClient[wire.ConnectResponse], error)
	Start(context.Context, *connect.Request[wire.StartRequest]) (*connect.ServerStreamForClient[wire.StartResponse], error)
}

// NewProcessClient constructs a client for the process.Process service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProcessClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProcessClient {
	baseURL = strings.TrimRight(baseURL, "/")
	processMethods := wire.File_internal_backend_e2b_wire_process_proto.Services().ByName("Process").Methods()
	return &processClient{
		connect: connect.NewClient[wire.ConnectRequest, wire.ConnectResponse](
			httpClient,
			baseURL+ProcessConnectProcedure,
			connect.WithSchema(processMethods.ByName("Connect")),
			connect.WithClientOptions(opts...),
		),
		start: connect.NewClient[wire.StartRequest, wire.StartResponse](
			httpClient,
			baseURL+ProcessStartProcedure,
			connect.WithSchema(processMethods.ByName("Start")),
			connect.WithClientOptions(opts...),
		),
	}
}

// processClient implements ProcessClient.
type processClient struct {
	connect *connect.Client[wire.ConnectRequest, wire.ConnectResponse]
	start   *connect.Client[wire.StartRequest, wire.StartResponse]
}

// Connect calls process.Process.Connect.
func (c *processClient) Connect(ctx context.Context, req *connect.Request[wire.ConnectRequest]) (*connect.ServerStreamForClient[wire.ConnectResponse], error) {
	return c.connect.CallServerStream(ctx, req)
}

// Start calls process.Process.Start.
func (c *processClient) Start(ctx context.Context, req *connect.Request[wire.StartRequest]) (*connect.ServerStreamForClient[wire.StartResponse], error) {
	return c.start.CallServerStream(ctx, req)
}

// ProcessHandler is an implementation of the process.Process service.
type ProcessHandler interface {
	Connect(context.Context, *connect.Request[wire.ConnectRequest], *connect.ServerStream[wire.ConnectResponse]) error
	Start(context.Context, *connect.Request[wire.StartRequest], *connect.ServerStream[wire.StartResponse]) error
}

// NewProcessHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProcessHandler(svc ProcessHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	processMethods := wire.File_internal_backend_e2b_wire_process_proto.Services().ByName("Process").Methods()
	processConnectHandler := connect.NewServerStreamHandler(
		ProcessConnectProcedure,
		svc.Connect,
		connect.WithSchema(processMethods.ByName("Connect")),
		connect.WithHandlerOptions(opts...),
	)
	processStartHandler := connect.NewServerStreamHandler(
		ProcessStartProcedure,
		svc.Start,
		connect.WithSchema(processMethods.ByName("Start")),
		connect.WithHandlerOptions(opts...),
	)
	return "/process.Process/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProcessConnectProcedure:
			processConnectHandler.ServeHTTP(w, r)
		case ProcessStartProcedure:
			processStartHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProcessHandler returns CodeUnimplemented from all methods.
type UnimplementedProcessHandler struct{}

func (UnimplementedProcessHandler) Connect(context.Context, *connect.Request[wire.ConnectRequest], *connect.ServerStream[wire.ConnectResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("process.Process.Connect is not implemented"))
}

func (UnimplementedProcessHandler) Start(context.Context, *connect.Request[wire.StartRequest], *connect.ServerStream[wire.StartResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("process.Process.Start is not implemented"))
}
