// Derived from E2B Runtime's Apache-2.0 envd process contract.
// Pinned source revision: 767ceb4b2ec0e598f512767c8da9e5e6618da368.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: internal/backend/e2b/wire/process.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Envs          map[string]string      `protobuf:"bytes,3,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd           *string                `protobuf:"bytes,4,opt,name=cwd,proto3,oneof" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessConfig) Reset() {
	*x = ProcessConfig{}
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessConfig) ProtoMessage() {}

func (x *ProcessConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessConfig.ProtoReflect.Descriptor instead.
func (*ProcessConfig) Descriptor() ([]byte, []int) {
	return file_internal_backend_e2b_wire_process_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessConfig) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *ProcessConfig) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProcessConfig) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *ProcessConfig) GetCwd() string {
	if x != nil && x.Cwd != nil {
		return *x.Cwd
	}
	return ""
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       *ProcessConfig         `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Tag           *string                `protobuf:"bytes,3,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	Stdin         *bool                  `protobuf:"varint,4,opt,name=stdin,proto3,oneof" json:"stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_internal_backend_e2b_wire_process_proto_rawDescGZIP(), []int{1}
}

func (x *StartRequest) GetProcess() *ProcessConfig {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *StartRequest) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

func (x *StartRequest) GetStdin() bool {
	if x != nil && x.Stdin != nil {
		return *x.Stdin
	}
	return false
}

type ProcessEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ProcessEvent_Start
	//	*ProcessEvent_Data
	//	*ProcessEvent_End
	//	*ProcessEvent_Keepalive
	Event         isProcessEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent) Reset() {
	*x = ProcessEvent{}
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent) ProtoMessage() {}

func (x *ProcessEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent) Descriptor() ([]byte, []int) {
	return file_internal_backend_e2b_wire_process_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessEvent) GetEvent() isProcessEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ProcessEvent) GetStart() *ProcessEvent_StartEvent {
	if x != nil {
		if x, ok := x.Event.(*ProcessEvent_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ProcessEvent) GetData() *ProcessEvent_DataEvent {
	if x != nil {
		if x, ok := x.Event.(*ProcessEvent_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ProcessEvent) GetEnd() *ProcessEvent_EndEvent {
	if x != nil {
		if x, ok := x.Event.(*ProcessEvent_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *ProcessEvent) GetKeepalive() *ProcessEvent_KeepAlive {
	if x != nil {
		if x, ok := x.Event.(*ProcessEvent_Keepalive); ok {
			return x.Keepalive
		}
	}
	return nil
}

type isProcessEvent_Event interface {
	isProcessEvent_Event()
}

type ProcessEvent_Start struct {
	Start *ProcessEvent_StartEvent `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ProcessEvent_Data struct {
	Data *ProcessEvent_DataEvent `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type ProcessEvent_End struct {
	End *ProcessEvent_EndEvent `protobuf:"bytes,3,opt,name=end,proto3,oneof"`
}

type ProcessEvent_Keepalive struct {
	Keepalive *ProcessEvent_KeepAlive `protobuf:"bytes,4,opt,name=keepalive,proto3,oneof"`
}

func (*ProcessEvent_Start) isProcessEvent_Event() {}

func (*ProcessEvent_Data) isProcessEvent_Event() {}

func (*ProcessEvent_End) isProcessEvent_Event() {}

func (*ProcessEvent_Keepalive) isProcessEvent_Event() {}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *ProcessEvent          `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_internal_backend_e2b_wire_process_proto_rawDescGZIP(), []int{3}
}

func (x *StartResponse) GetEvent() *ProcessEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *ProcessEvent          `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_backend_e2b_wire_process_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectResponse) GetEvent() *ProcessEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       *ProcessSelector       `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_backend_e2b_wire_process_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectRequest) GetProcess() *ProcessSelector {
	if x != nil {
		return x.Process
	}
	return nil
}

type ProcessSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Selector:
	//
	//	*ProcessSelector_Pid
	//	*ProcessSelector_Tag
	Selector      isProcessSelector_Selector `protobuf_oneof:"selector"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessSelector) Reset() {
	*x = ProcessSelector{}
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSelector) ProtoMessage() {}

func (x *ProcessSelector) ProtoReflect() protoreflect.Message {
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSelector.ProtoReflect.Descriptor instead.
func (*ProcessSelector) Descriptor() ([]byte, []int) {
	return file_internal_backend_e2b_wire_process_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessSelector) GetSelector() isProcessSelector_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *ProcessSelector) GetPid() uint32 {
	if x != nil {
		if x, ok := x.Selector.(*ProcessSelector_Pid); ok {
			return x.Pid
		}
	}
	return 0
}

func (x *ProcessSelector) GetTag() string {
	if x != nil {
		if x, ok := x.Selector.(*ProcessSelector_Tag); ok {
			return x.Tag
		}
	}
	return ""
}

type isProcessSelector_Selector interface {
	isProcessSelector_Selector()
}

type ProcessSelector_Pid struct {
	Pid uint32 `protobuf:"varint,1,opt,name=pid,proto3,oneof"`
}

type ProcessSelector_Tag struct {
	Tag string `protobuf:"bytes,2,opt,name=tag,proto3,oneof"`
}

func (*ProcessSelector_Pid) isProcessSelector_Selector() {}

func (*ProcessSelector_Tag) isProcessSelector_Selector() {}

type ProcessEvent_StartEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent_StartEvent) Reset() {
	*x = ProcessEvent_StartEvent{}
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent_StartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent_StartEvent) ProtoMessage() {}

func (x *ProcessEvent_StartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent_StartEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent_StartEvent) Descriptor() ([]byte, []int) {
	return file_internal_backend_e2b_wire_process_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ProcessEvent_StartEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ProcessEvent_DataEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*ProcessEvent_DataEvent_Stdout
	//	*ProcessEvent_DataEvent_Stderr
	//	*ProcessEvent_DataEvent_Pty
	Output        isProcessEvent_DataEvent_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent_DataEvent) Reset() {
	*x = ProcessEvent_DataEvent{}
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent_DataEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent_DataEvent) ProtoMessage() {}

func (x *ProcessEvent_DataEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent_DataEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent_DataEvent) Descriptor() ([]byte, []int) {
	return file_internal_backend_e2b_wire_process_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ProcessEvent_DataEvent) GetOutput() isProcessEvent_DataEvent_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ProcessEvent_DataEvent) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Output.(*ProcessEvent_DataEvent_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ProcessEvent_DataEvent) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Output.(*ProcessEvent_DataEvent_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ProcessEvent_DataEvent) GetPty() []byte {
	if x != nil {
		if x, ok := x.Output.(*ProcessEvent_DataEvent_Pty); ok {
			return x.Pty
		}
	}
	return nil
}

type isProcessEvent_DataEvent_Output interface {
	isProcessEvent_DataEvent_Output()
}

type ProcessEvent_DataEvent_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ProcessEvent_DataEvent_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ProcessEvent_DataEvent_Pty struct {
	Pty []byte `protobuf:"bytes,3,opt,name=pty,proto3,oneof"`
}

func (*ProcessEvent_DataEvent_Stdout) isProcessEvent_DataEvent_Output() {}

func (*ProcessEvent_DataEvent_Stderr) isProcessEvent_DataEvent_Output() {}

func (*ProcessEvent_DataEvent_Pty) isProcessEvent_DataEvent_Output() {}

type ProcessEvent_EndEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"zigzag32,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Exited        bool                   `protobuf:"varint,2,opt,name=exited,proto3" json:"exited,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error         *string                `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent_EndEvent) Reset() {
	*x = ProcessEvent_EndEvent{}
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent_EndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent_EndEvent) ProtoMessage() {}

func (x *ProcessEvent_EndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent_EndEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent_EndEvent) Descriptor() ([]byte, []int) {
	return file_internal_backend_e2b_wire_process_proto_rawDescGZIP(), []int{2, 2}
}

func (x *ProcessEvent_EndEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ProcessEvent_EndEvent) GetExited() bool {
	if x != nil {
		return x.Exited
	}
	return false
}

func (x *ProcessEvent_EndEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessEvent_EndEvent) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ProcessEvent_KeepAlive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent_KeepAlive) Reset() {
	*x = ProcessEvent_KeepAlive{}
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent_KeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent_KeepAlive) ProtoMessage() {}

func (x *ProcessEvent_KeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_internal_backend_e2b_wire_process_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent_KeepAlive.ProtoReflect.Descriptor instead.
func (*ProcessEvent_KeepAlive) Descriptor() ([]byte, []int) {
	return file_internal_backend_e2b_wire_process_proto_rawDescGZIP(), []int{2, 3}
}

var File_internal_backend_e2b_wire_process_proto protoreflect.FileDescriptor

const file_internal_backend_e2b_wire_process_proto_rawDesc = "" +
	"\n" +
	"'internal/backend/e2b/wire/process.proto\x12\aprocess\"\xc3\x01\n" +
	"\rProcessConfig\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x124\n" +
	"\x04envs\x18\x03 \x03(\v2 .process.ProcessConfig.EnvsEntryR\x04envs\x12\x15\n" +
	"\x03cwd\x18\x04 \x01(\tH\x00R\x03cwd\x88\x01\x01\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04_cwd\"\x84\x01\n" +
	"\fStartRequest\x120\n" +
	"\aprocess\x18\x01 \x01(\v2\x16.process.ProcessConfigR\aprocess\x12\x15\n" +
	"\x03tag\x18\x03 \x01(\tH\x00R\x03tag\x88\x01\x01\x12\x19\n" +
	"\x05stdin\x18\x04 \x01(\bH\x01R\x05stdin\x88\x01\x01B\x06\n" +
	"\x04_tagB\b\n" +
	"\x06_stdin\"\x87\x04\n" +
	"\fProcessEvent\x128\n" +
	"\x05start\x18\x01 \x01(\v2 .process.ProcessEvent.StartEventH\x00R\x05start\x125\n" +
	"\x04data\x18\x02 \x01(\v2\x1f.process.ProcessEvent.DataEventH\x00R\x04data\x122\n" +
	"\x03end\x18\x03 \x01(\v2\x1e.process.ProcessEvent.EndEventH\x00R\x03end\x12?\n" +
	"\tkeepalive\x18\x04 \x01(\v2\x1f.process.ProcessEvent.KeepAliveH\x00R\tkeepalive\x1a\x1e\n" +
	"\n" +
	"StartEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x1a]\n" +
	"\tDataEvent\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x12\n" +
	"\x03pty\x18\x03 \x01(\fH\x00R\x03ptyB\b\n" +
	"\x06output\x1a|\n" +
	"\bEndEvent\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x11R\bexitCode\x12\x16\n" +
	"\x06exited\x18\x02 \x01(\bR\x06exited\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\x1a\v\n" +
	"\tKeepAliveB\a\n" +
	"\x05event\"<\n" +
	"\rStartResponse\x12+\n" +
	"\x05event\x18\x01 \x01(\v2\x15.process.ProcessEventR\x05event\">\n" +
	"\x0fConnectResponse\x12+\n" +
	"\x05event\x18\x01 \x01(\v2\x15.process.ProcessEventR\x05event\"D\n" +
	"\x0eConnectRequest\x122\n" +
	"\aprocess\x18\x01 \x01(\v2\x18.process.ProcessSelectorR\aprocess\"E\n" +
	"\x0fProcessSelector\x12\x12\n" +
	"\x03pid\x18\x01 \x01(\rH\x00R\x03pid\x12\x12\n" +
	"\x03tag\x18\x02 \x01(\tH\x00R\x03tagB\n" +
	"\n" +
	"\bselector2\x83\x01\n" +
	"\aProcess\x12>\n" +
	"\aConnect\x12\x17.process.ConnectRequest\x1a\x18.process.ConnectResponse0\x01\x128\n" +
	"\x05Start\x12\x15.process.StartRequest\x1a\x16.process.StartResponse0\x01B=Z;github.com/infercrane/brezel/internal/backend/e2b/wire;wireb\x06proto3"

var (
	file_internal_backend_e2b_wire_process_proto_rawDescOnce sync.Once
	file_internal_backend_e2b_wire_process_proto_rawDescData []byte
)

func file_internal_backend_e2b_wire_process_proto_rawDescGZIP() []byte {
	file_internal_backend_e2b_wire_process_proto_rawDescOnce.Do(func() {
		file_internal_backend_e2b_wire_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_backend_e2b_wire_process_proto_rawDesc), len(file_internal_backend_e2b_wire_process_proto_rawDesc)))
	})
	return file_internal_backend_e2b_wire_process_proto_rawDescData
}

var file_internal_backend_e2b_wire_process_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_backend_e2b_wire_process_proto_goTypes = []any{
	(*ProcessConfig)(nil),           // 0: process.ProcessConfig
	(*StartRequest)(nil),            // 1: process.StartRequest
	(*ProcessEvent)(nil),            // 2: process.ProcessEvent
	(*StartResponse)(nil),           // 3: process.StartResponse
	(*ConnectResponse)(nil),         // 4: process.ConnectResponse
	(*ConnectRequest)(nil),          // 5: process.ConnectRequest
	(*ProcessSelector)(nil),         // 6: process.ProcessSelector
	nil,                             // 7: process.ProcessConfig.EnvsEntry
	(*ProcessEvent_StartEvent)(nil), // 8: process.ProcessEvent.StartEvent
	(*ProcessEvent_DataEvent)(nil),  // 9: process.ProcessEvent.DataEvent
	(*ProcessEvent_EndEvent)(nil),   // 10: process.ProcessEvent.EndEvent
	(*ProcessEvent_KeepAlive)(nil),  // 11: process.ProcessEvent.KeepAlive
}
var file_internal_backend_e2b_wire_process_proto_depIdxs = []int32{
	7,  // 0: process.ProcessConfig.envs:type_name -> process.ProcessConfig.EnvsEntry
	0,  // 1: process.StartRequest.process:type_name -> process.ProcessConfig
	8,  // 2: process.ProcessEvent.start:type_name -> process.ProcessEvent.StartEvent
	9,  // 3: process.ProcessEvent.data:type_name -> process.ProcessEvent.DataEvent
	10, // 4: process.ProcessEvent.end:type_name -> process.ProcessEvent.EndEvent
	11, // 5: process.ProcessEvent.keepalive:type_name -> process.ProcessEvent.KeepAlive
	2,  // 6: process.StartResponse.event:type_name -> process.ProcessEvent
	2,  // 7: process.ConnectResponse.event:type_name -> process.ProcessEvent
	6,  // 8: process.ConnectRequest.process:type_name -> process.ProcessSelector
	5,  // 9: process.Process.Connect:input_type -> process.ConnectRequest
	1,  // 10: process.Process.Start:input_type -> process.StartRequest
	4,  // 11: process.Process.Connect:output_type -> process.ConnectResponse
	3,  // 12: process.Process.Start:output_type -> process.StartResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_internal_backend_e2b_wire_process_proto_init() }
func file_internal_backend_e2b_wire_process_proto_init() {
	if File_internal_backend_e2b_wire_process_proto != nil {
		return
	}
	file_internal_backend_e2b_wire_process_proto_msgTypes[0].OneofWrappers = []any{}
	file_internal_backend_e2b_wire_process_proto_msgTypes[1].OneofWrappers = []any{}
	file_internal_backend_e2b_wire_process_proto_msgTypes[2].OneofWrappers = []any{
		(*ProcessEvent_Start)(nil),
		(*ProcessEvent_Data)(nil),
		(*ProcessEvent_End)(nil),
		(*ProcessEvent_Keepalive)(nil),
	}
	file_internal_backend_e2b_wire_process_proto_msgTypes[6].OneofWrappers = []any{
		(*ProcessSelector_Pid)(nil),
		(*ProcessSelector_Tag)(nil),
	}
	file_internal_backend_e2b_wire_process_proto_msgTypes[9].OneofWrappers = []any{
		(*ProcessEvent_DataEvent_Stdout)(nil),
		(*ProcessEvent_DataEvent_Stderr)(nil),
		(*ProcessEvent_DataEvent_Pty)(nil),
	}
	file_internal_backend_e2b_wire_process_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_backend_e2b_wire_process_proto_rawDesc), len(file_internal_backend_e2b_wire_process_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_backend_e2b_wire_process_proto_goTypes,
		DependencyIndexes: file_internal_backend_e2b_wire_process_proto_depIdxs,
		MessageInfos:      file_internal_backend_e2b_wire_process_proto_msgTypes,
	}.Build()
	File_internal_backend_e2b_wire_process_proto = out.File
	file_internal_backend_e2b_wire_process_proto_goTypes = nil
	file_internal_backend_e2b_wire_process_proto_depIdxs = nil
}
